// Main Block component
import BlockComponent from './components/Block';
export { default as Block } from './components/Block';
export type { BlockProps } from './components/Block';

// Named block utilities
export { createNamedBlock, createTypedBlock, withBlockMetadata } from './components/NamedBlock';
export type { NamedBlockProps } from './components/NamedBlock';

// Author block utilities
export { default as AuthorBlock, createAuthorBlock, createAuthorNamespace } from './components/AuthorBlock';
export type { AuthorBlockProps } from './components/AuthorBlock';

// Registry and federation utilities
export { blockRegistry, createRegistryEntry } from './utils/blockRegistry';
export type { BlockRegistry, BlockRegistryEntry, AuthorNamespaceRegistry } from './utils/blockRegistry';
export { federationLoader } from './utils/federationLoader';
export type { BlockMetadata, FederationModule, MountFunction } from './utils/federationLoader';

// Configuration
export { configure } from './config';
export type { MextBlockConfig } from './config';

// Pre-created named components (these will be dynamically generated)
// For now, we'll create some example components manually
// In the future, these can be auto-generated by mexty

// Example named components - these can be updated via CLI
import { createNamedBlock, createTypedBlock } from './components/NamedBlock';
import { blockRegistry } from './utils/blockRegistry';
import { federationLoader } from './utils/federationLoader';
import { configure } from './config';
import { withBlockMetadata } from './components/NamedBlock';

// Virtual Game component example
export const VirtualGame = createNamedBlock('VirtualGame');

// 3D Scene component example  
export const ThreeScene = createNamedBlock('ThreeScene');

// Chart component example
export const Chart = createNamedBlock('Chart');

// Form component example
export const Form = createNamedBlock('Form');

// Video Player component example
export const VideoPlayer = createNamedBlock('VideoPlayer');

// Code Editor component example
export const CodeEditor = createNamedBlock('CodeEditor');

// Image Gallery component example
export const ImageGallery = createNamedBlock('ImageGallery');

// Analytics Dashboard component example
export const AnalyticsDashboard = createNamedBlock('AnalyticsDashboard');

// Note: In production, these named exports would be generated automatically
// by the mexty based on the registry from the server

// Re-export everything as default for convenience
const MextBlock = {
  Block: BlockComponent,
  VirtualGame,
  ThreeScene,
  Chart,
  Form,
  VideoPlayer,
  CodeEditor,
  ImageGallery,
  AnalyticsDashboard,
  createNamedBlock,
  createTypedBlock,
  withBlockMetadata,
  blockRegistry,
  federationLoader,
  configure
};

export default MextBlock; 
// Auto-generated named exports
export * from './namedExports';
