// Auto-generated named exports for mext-block components
// This file is automatically generated by mexty sync command
// Do not edit manually - changes will be overwritten

import { createNamedBlock } from './components/NamedBlock';

// The exports in this file are automatically generated based on the server registry
// When you run `mexty sync`, this file is updated with the latest components

// Default exports (will be replaced during sync)
export const VirtualGame = createNamedBlock('VirtualGame');
export const ThreeScene = createNamedBlock('ThreeScene');  
export const Chart = createNamedBlock('Chart');
export const Form = createNamedBlock('Form');
export const VideoPlayer = createNamedBlock('VideoPlayer');
export const CodeEditor = createNamedBlock('CodeEditor');
export const ImageGallery = createNamedBlock('ImageGallery');
export const AnalyticsDashboard = createNamedBlock('AnalyticsDashboard');

// This comment is used by mexty to identify where to insert new exports
// MEXT_CLI_EXPORTS_MARKER
